
name: 'Terraform plan'

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform-plan:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: login to azure cli
      uses: azure/login@v1      

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that planning
    - name: Terraform plan
      run: terraform plan

   
